var DispatchConstants = {
  LOGIN_SUCCESS : "LOGIN_SUCCESS",
  LOGIN_FAILURE : "LOGIN_FAILURE",
  REGISTRATION_SUCCESS : "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE : "REGISTRATION_FAILURE",
  LOGGED_IN : "LOGGED_IN",
  LOGGED_OUT : "LOGGED_OUT",
  ALERT_SUCCESS : "ALERT_SUCCESS",
  ALERT_INFO : "ALERT_INFO",
  ALERT_WARNING : "ALERT_WARNING",
  ALERT_DANGER : "ALERT_DANGER"
};

module.exports = DispatchConstants;
