var DispatchConstants = {
  LOGIN_SUCCESS : "LOGIN_SUCCESS",
  LOGIN_FAILURE : "LOGIN_FAILURE",
  REGISTRATION_SUCCESS : "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE : "REGISTRATION_FAILURE"
};

module.exports = DispatchConstants;
