var DispatchConstants = {
  LOGIN_SUCCESS : "LOGIN_SUCCESS",
  LOGIN_FAILURE : "LOGIN_FAILURE",
  REGISTRATION_SUCCESS : "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE : "REGISTRATION_FAILURE",
  LOGGED_IN : "LOGGED_IN",
  LOGGED_OUT : "LOGGED_OUT"
};

module.exports = DispatchConstants;
